apiVersion: apps/v1
kind: Deployment
metadata:
  name: papaya-orderingsystem-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papaya-orderingsystem-be
  template:
    metadata:
      labels:
        app: papaya-orderingsystem-be
    spec:
      containers:
        - image: l1n77/papaya-orderingsystem-be
          imagePullPolicy: Always
          name: papaya-orderingsystem-be
          envFrom:
            - configMapRef:
                name: config-papaya



---
apiVersion: v1
kind: Service
metadata:
  name: papaya-orderingsystem-be
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "papaya-orderingsystem-be"
      port: 8080
  selector:
    app: papaya-orderingsystem-be
