apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: papaya-orderingsystem-be
configMapGenerator:
  - name: config-app
    files:
      - config.yaml
resources:
  - kubernetes.yaml