apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: config-papaya-pw
    files:
      - config-pw.yaml
  - name: config-papaya-user
    files:
      - config-user.yaml
resources:
  - kubernetes.yml