name: deploy
on:
  workflow_run:
    workflows: ["build"]
    branches:
      - main
      - feature/secret
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: destroy old pipeline
        uses: okteto/destroy-pipeline@latest
        with:
          name: papaya-orderingsystem-be

      - name: okteto pipeline
        uses: okteto/pipeline@latest
        with:
          name: papaya-orderingsystem-be
