name: quarkus-build
on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: build and package Quarkus
        run: |
          chmod +x mvnw |
          sudo ./mvnw package
        env:
          MAIL_PASSWORD: "123"
          MAIL_USERNAME: "123"